Repository decide-single-juanymedio-fork-1/decide, pull requests merged in 2023-12, with the labels that each got.

#7 Feat: Lenguaje Ofensivo
  decide/voting/migrations/0005_alter_question_desc_alter_voting_desc.py
  decide/voting/migrations/0006_alter_questionoption_option_alter_voting_name.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/tests.py
  decide/voting/validators.py
Labels: code, High

#12 Feat: Exportar Censo
  decide/census/admin.py
  decide/census/tests.py
  decide/census/urls.py
  decide/census/views.py
Labels: code, Low

#23 Feat: Importar censo desde excel
  decide/census/admin.py
  decide/census/forms.py
  decide/census/templates/importar_censo.html
  decide/census/tests.py
  decide/census/urls.py
  decide/census/views.py
Labels: code, Low

#27 Fix : Formulario registro y tests de carga
  decide/booth/templates/register.html
  decide/booth/tests.py
  loadtest/locustfile.py
Labels: bug

#29 Feat: Traducciones
  decide/booth/templates/booth/booth.html
  decide/booth/views.py
  decide/decide/settings.py
  decide/decide/urls.py
  decide/locale/en/LC_MESSAGES/django.mo
  decide/locale/en/LC_MESSAGES/django.po
  decide/locale/es/LC_MESSAGES/django.mo
  decide/locale/es/LC_MESSAGES/django.po
  decide/locale/fr/LC_MESSAGES/django.mo
  decide/locale/fr/LC_MESSAGES/django.po
Labels: code, Low

#32 Feat: Docker
  .github/workflows/django.yml
  decide/booth/views.py
  decide/decide/urls.py
  docker/Dockerfile
  docker/docker-compose.yml
  docker/docker-settings.py
Labels: code, High

#34 Feat: Despliegue Vagrant funcionando
  vagrant/Vagrantfile
  vagrant/django.yml
  vagrant/files/settings.py
  vagrant/packages.yml
  vagrant/python.yml
Labels: High

#36 Fix: Docker
  docker/Dockerfile
  docker/docker-settings.py
Labels: bug, code

#38 feat: Añadido campo email al registro
  decide/booth/forms.py
  decide/booth/migrations/0004_form_email.py
  decide/booth/models.py
  decide/booth/templates/register.html
  decide/booth/tests.py
Labels: code, High

#43 Feat: Inicio sesión admin
  decide/booth/tests.py
  decide/booth/views.py
Labels: code, Medium

#44 Feat: Iniciar sesión email
  decide/booth/templates/login.html
  decide/booth/tests.py
  decide/booth/views.py
Labels: code, Medium

#56 feat: Página principal
  decide/booth/templates/home.html
  decide/booth/tests.py
  decide/booth/urls.py
  decide/booth/views.py
Labels: code, High

#60 Fix - Conectar el registro de usuario a la página principal
  decide/booth/templates/login.html
  decide/booth/templates/register.html
  decide/booth/templates/thanks.html
  decide/booth/tests.py
  decide/booth/views.py
Labels: code, Low

#64 Feat: Plantilla de mensaje de commits actualizada
  .gitmessage.txt
Labels: documentation, Low

#62 Feat: Mostrar grafica de resultado
  decide/visualizer/templates/visualizer/visualizer.html
Labels: code, Low

#65 Feat - Notificación nueva votación
  decide/booth/templates/home.html
  decide/booth/templates/login.html
  decide/booth/templates/register.html
  decide/booth/templates/thanks.html
  decide/booth/tests.py
  decide/booth/views.py
Labels: code, High

#72 Fix : loadtest register
  loadtest/locustfile.py
Labels: bug, Medium

#70 Feat: Resetear votacion
  decide/voting/admin.py
  decide/voting/models.py
  decide/voting/tests.py
  decide/voting/views.py
Labels: code, Medium

#76 Fix: Error Codacy
  decide/booth/forms.py
  decide/booth/tests.py
  decide/booth/views.py
  decide/census/admin.py
  decide/census/tests.py
  decide/voting/validators.py
Labels: bug, Critical

#78 fix: Errores Codacy
  decide/census/tests.py
  decide/census/views.py
Labels: code, Critical

#74 Release 1.0.0
  .github/workflows/django.yml
  .gitmessage.txt
  decide/authentication/views.py
  decide/booth/forms.py
  decide/booth/migrations/0001_initial.py
  decide/booth/migrations/0002_delete_user.py
  decide/booth/migrations/0003_initial.py
  decide/booth/migrations/0004_form_email.py
  decide/booth/models.py
  decide/booth/templates/booth/booth.html
  decide/booth/templates/change_user.html
  decide/booth/templates/home.html
  decide/booth/templates/login.html
  decide/booth/templates/register.html
  decide/booth/templates/thanks.html
  decide/booth/tests.py
  decide/booth/urls.py
  decide/booth/views.py
  decide/census/admin.py
  decide/census/forms.py
  decide/census/templates/importar_censo.html
  decide/census/tests.py
  decide/census/urls.py
  decide/census/views.py
  decide/decide/settings.py
  decide/decide/urls.py
  decide/locale/en/LC_MESSAGES/django.mo
  decide/locale/en/LC_MESSAGES/django.po
  decide/locale/es/LC_MESSAGES/django.mo
  decide/locale/es/LC_MESSAGES/django.po
  decide/locale/fr/LC_MESSAGES/django.mo
  decide/locale/fr/LC_MESSAGES/django.po
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/views.py
  decide/voting/admin.py
  decide/voting/migrations/0005_alter_question_desc_alter_voting_desc.py
  decide/voting/migrations/0006_alter_questionoption_option_alter_voting_name.py
  decide/voting/migrations/0007_preference_apportionment.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/tests.py
  decide/voting/validators.py
  decide/voting/views.py
  doc/diario-de-equipo.md
  docker/Dockerfile
  docker/docker-compose.yml
  docker/docker-settings.py
  loadtest/locustfile.py
  requirements.txt
  vagrant/Vagrantfile
  vagrant/django.yml
  vagrant/files/settings.py
  vagrant/packages.yml
  vagrant/python.yml
Labels: code, Critical

#69 Feat: Tests selenium
  .github/workflows/django.yml
  decide/booth/tests_selendium.py
Labels: code, Low

#81 Fix- selenium tests en workflow
  .github/workflows/django.yml
  decide/booth/tests_selendium.py
Labels: bug, Critical

#83 Feat - Release 1.0.1
  .github/workflows/django.yml
Labels: code, Critical

#85 Feat: Cambiar fondo #84
  decide/booth/templates/login.html
Labels: code, Critical

#86 Develop
  decide/booth/templates/login.html
Labels: code, Critical
